const START_LOADING = "START_LOADING";
const STOP_LOADING = "STOP_LOADING";
const SPANISH_MESSAGE = "SPANISH_MESSAGE";
const ENGLISH_MESSAGE = "ENGLISH_MESSAGE";

export { START_LOADING, STOP_LOADING, SPANISH_MESSAGE, ENGLISH_MESSAGE };
