const START_LOADING = "START_LOADING";
const STOP_LOADING = "STOP_LOADING";
const SPANISH_MESSAGE = "SPANISH_MESSAGE";
const ENGLISH_MESSAGE = "ENGLISH_MESSAGE";
const AUTH = {
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT"
};
const SET_USER_STATUS = "SET_USER_STATUS";

export {
  START_LOADING,
  STOP_LOADING,
  SPANISH_MESSAGE,
  ENGLISH_MESSAGE,
  AUTH,
  SET_USER_STATUS
};
