const START_LOADING = "START_LOADING";
const STOP_LOADING = "STOP_LOADING";
const AUTH = {
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT"
};
const SET_USER_STATUS = "SET_USER_STATUS";
const COOKIE_ACTION_TYPES = {
  SET_COOKIES: "SET_COOKIES",
  ADD_COOKIE: "ADD_COOKIES",
  REMOVE_COOKIE: "REMOVE_COOKIE",
  UPDATE_COOKIE: "UPDATE_COOKIE"
};

export {
  START_LOADING,
  STOP_LOADING,
  AUTH,
  SET_USER_STATUS,
  COOKIE_ACTION_TYPES
};
